spring:
  redis:
    host: localhost
    password: 123
    port: 6379
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: lb://provider
          filters:
            - AddRequestParameter=name,robot
          predicates:
            - Path=/test_get
#        - id: hystrix_route
#          uri: http://localhost:8201
#          predicates:
#            - Method=GET
#          filters:
#            - name: Hystrix
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/fallback
#        - id: requestratelimiter_route
#          uri: http://localhost:1113
#          predicates:
#            - Method=GET
#          filters:
#            - name: RequestRateLimiter
#              args:
#                #每秒允许处理的请求数量
#                redis-rate-limiter.replenishRate: 1
#                #每秒最大处理的请求数量
#                redis-rate-limiter.burstCapacity: 2
#                #限流策略，对应策略的Bean
#                key-resolver: "#{@ipKeyResolver}"
        - id: retry_route
          uri: http://localhost:1113
          predicates:
          - Method=GET
          filters:
            - name: Retry
              args:
                #需要进行重试的次数
                retries: 1
                #返回哪个状态码需要进行重试，返回状态码为5XX进行重试
                statuses: INTERNAL_SERVER_ERROR
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
      discovery:
        locator:
          enabled: true # 开启自动代理
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug
